Husky precommit hook fix

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -2,11 +2,10 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 branch=$(git branch | grep '*' | sed 's/* //')
-branchRegex='(master|main|hotfix|develop)|(feat|chore|fix)\/[a-zA-z\d]+(\-[a-zA-Z\d]+)*'
+branchRegex='^(master|main|hotfix|develop)|((feat|chore|fix|ci)/[a-zA-Z0-9]+(-[a-zA-Z0-9])*)$'
 
-if [[ $branch =~ $branchRegex ]]
-then
+if [[ $branch =~ $branchRegex ]]; then
   exit 0
 else
-  echo "Branch name is invalid" && exit 1
+  echo "Branch name is invalid." && exit 1
 fi
